//! Satellite render-plan DTOs (gap-4e2db371).
//!
//! A remote corpus daemon cannot materialize files on the operator's
//! machine: provider-memory renders and repo-owned knowledge/gap placement
//! need local filesystem access the daemon does not have. The daemon
//! computes WHAT would be written and serves it as a plan over
//! `GET /render/plan`; the satellite client (`bro render`) owns the local
//! writes and confirms repo-owned placements via `POST /render/ack`.
//!
//! The client performs only generic operations: whole-file writes gated on
//! the blackbox-generated header, managed-region marker splices, and
//! relative-path record drops. No render semantics cross the boundary
//! (harness-daemon-boundary §7: clients never link the daemon's crates).

use serde::{Deserialize, Serialize};

/// The blackbox-generated header a project provider file must carry (or the
/// file must be absent) for a whole-file write to proceed. Mirrors the
/// daemon-side `should_write_project_projection` guard.
pub const GENERATED_HEADER_PREFIX: &str = "<!-- Generated by blackbox";

/// Managed-region markers for global provider files. Mirrors the daemon's
/// render module; carried here so the client never links it.
pub const MANAGED_START: &str = "<!-- bb:managed-start -->";
pub const MANAGED_END: &str = "<!-- bb:managed-end -->";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenderPlanV1 {
    /// Envelope version; bump on breaking shape changes.
    pub version: u32,
    /// Hash over every item/record payload: a cheap staleness probe for
    /// `bro render --check` and doctor-style comparisons.
    pub render_hash: String,
    pub items: Vec<RenderPlanItemV1>,
    /// Repo-owned records the daemon could not place (no visible checkout);
    /// the client writes them under the project dir and acks their ids.
    pub repo_records: Vec<RepoRecordV1>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RenderPlanItemV1 {
    /// A fully-generated project provider file. The client writes it at
    /// `<project>/<file_name>` only when the existing file is absent or
    /// carries [`GENERATED_HEADER_PREFIX`].
    WholeFile { file_name: String, contents: String },
    /// A managed region for a global provider file. `target` is a logical
    /// key (`common`, `claude`, `agents`, `gemini`); the CLIENT maps it to
    /// its own local path (the daemon's paths would be wrong on a remote
    /// host). The client splices `block` between the managed markers,
    /// appending the region when the markers are absent, and refuses to
    /// clobber a non-empty existing region with an empty block.
    ManagedRegion { target: String, block: String },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepoRecordV1 {
    /// Owning store: `knowledge` or `gaps`.
    pub store: String,
    pub id: String,
    /// Path relative to the project dir (e.g. `.bbox/knowledge/<id>.json`).
    pub relpath: String,
    /// Exact committed-file serialization.
    pub contents: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenderAckV1 {
    pub project: String,
    #[serde(default)]
    pub knowledge_ids: Vec<String>,
    #[serde(default)]
    pub gap_ids: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenderAckResponseV1 {
    pub knowledge_marked: usize,
    pub gaps_marked: usize,
}
