//! TLS for the TCP owner listener.
//!
//! fleetd has one identity: a self-signed certificate and its private key,
//! generated by `fleetd identity init` and stored beside the socket and the
//! token. The daemon pins that certificate by the SHA-256 digest of its DER
//! encoding, printed by `identity init` and `identity show`, so no authority
//! and no name check is involved: a connection is accepted by the daemon only
//! when the certificate fleetd presents is byte for byte the pinned one, and
//! the bearer token then travels inside that channel. Rotating the identity
//! means generating a new one and pinning the new digest.
//!
//! The key file is written owner-only. The certificate is public.

use std::net::IpAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use rustls_pki_types::pem::PemObject;
use rustls_pki_types::{CertificateDer, PrivateKeyDer};

pub const CERTIFICATE_FILE: &str = "fleetd-tls.crt";
pub const PRIVATE_KEY_FILE: &str = "fleetd-tls.key";

/// Where an identity lives: the certificate and the key, in one directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IdentityPaths {
    pub certificate: PathBuf,
    pub private_key: PathBuf,
}

impl IdentityPaths {
    pub fn in_dir(dir: impl AsRef<Path>) -> Self {
        let dir = dir.as_ref();
        Self {
            certificate: dir.join(CERTIFICATE_FILE),
            private_key: dir.join(PRIVATE_KEY_FILE),
        }
    }
}

/// A loaded identity: what the listener presents and what the daemon pins.
pub struct Identity {
    certificate: CertificateDer<'static>,
    private_key: PrivateKeyDer<'static>,
}

impl Identity {
    /// Generate a fresh self-signed identity naming `names` (IP addresses
    /// and DNS names the listener may be reached at) and write it to
    /// `paths`. Refuses to overwrite an existing identity: the daemon pins
    /// it, so replacing it silently would cut the daemon off.
    pub fn generate(paths: &IdentityPaths, names: &[String]) -> anyhow::Result<Self> {
        if paths.certificate.exists() || paths.private_key.exists() {
            anyhow::bail!(
                "a fleetd identity already exists at {}; remove it first to generate a new one, then pin the new digest in the daemon",
                paths.certificate.display()
            );
        }
        let subject_alt_names: Vec<String> = if names.is_empty() {
            vec!["fleetd".to_string()]
        } else {
            names.to_vec()
        };
        let certified = rcgen::generate_simple_self_signed(subject_alt_names)?;
        write_private(
            &paths.private_key,
            certified.key_pair.serialize_pem().as_bytes(),
        )?;
        write_public(&paths.certificate, certified.cert.pem().as_bytes())?;
        Self::load(paths)
    }

    /// Load an identity written by [`Identity::generate`].
    pub fn load(paths: &IdentityPaths) -> anyhow::Result<Self> {
        let certificate = CertificateDer::from_pem_file(&paths.certificate).map_err(|error| {
            anyhow::anyhow!(
                "reading the fleetd certificate {}: {error}",
                paths.certificate.display()
            )
        })?;
        let private_key = PrivateKeyDer::from_pem_file(&paths.private_key).map_err(|error| {
            anyhow::anyhow!(
                "reading the fleetd private key {}: {error}",
                paths.private_key.display()
            )
        })?;
        Ok(Self {
            certificate,
            private_key,
        })
    }

    /// The SHA-256 digest of the DER certificate, lowercase hex: the value the
    /// daemon pins.
    pub fn fingerprint(&self) -> String {
        certificate_fingerprint(&self.certificate)
    }

    pub fn certificate(&self) -> &CertificateDer<'static> {
        &self.certificate
    }

    /// The acceptor that wraps every TCP owner connection. No client
    /// certificate is requested: the bearer token authenticates the daemon
    /// inside the channel, as it does over the Unix socket.
    pub fn acceptor(&self) -> anyhow::Result<tokio_rustls::TlsAcceptor> {
        let config = rustls::ServerConfig::builder()
            .with_no_client_auth()
            .with_single_cert(vec![self.certificate.clone()], self.private_key.clone_key())?;
        Ok(tokio_rustls::TlsAcceptor::from(Arc::new(config)))
    }
}

/// Lowercase hex SHA-256 of a DER certificate.
pub fn certificate_fingerprint(certificate: &CertificateDer<'_>) -> String {
    let digest = ring::digest::digest(&ring::digest::SHA256, certificate.as_ref());
    digest
        .as_ref()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

/// The names to put in a generated certificate for the addresses the
/// listener will serve: the IP of each address. Names are informational
/// under pinning, so the list only has to be well formed.
pub fn names_for_addresses(addresses: &[std::net::SocketAddr]) -> Vec<String> {
    let mut names: Vec<String> = addresses
        .iter()
        .map(|address| match address.ip() {
            IpAddr::V4(ip) => ip.to_string(),
            IpAddr::V6(ip) => ip.to_string(),
        })
        .collect();
    names.sort();
    names.dedup();
    names
}

/// The certificate is public: created once, never replaced in place.
fn write_public(path: &Path, bytes: &[u8]) -> anyhow::Result<()> {
    use std::io::Write as _;
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|error| anyhow::anyhow!("creating {}: {error}", path.display()))?;
    file.write_all(bytes)?;
    file.sync_all()?;
    Ok(())
}

fn write_private(path: &Path, bytes: &[u8]) -> anyhow::Result<()> {
    use std::io::Write as _;
    use std::os::unix::fs::OpenOptionsExt as _;
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)
        .map_err(|error| anyhow::anyhow!("creating {}: {error}", path.display()))?;
    file.write_all(bytes)?;
    file.sync_all()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_identity_is_generated_once_loaded_back_and_pinned_by_its_digest() {
        let dir = tempfile::tempdir().unwrap();
        let paths = IdentityPaths::in_dir(dir.path());
        let generated = Identity::generate(&paths, &["127.0.0.1".to_string()]).unwrap();
        let loaded = Identity::load(&paths).unwrap();
        assert_eq!(generated.fingerprint(), loaded.fingerprint());
        assert_eq!(generated.fingerprint().len(), 64);
        assert!(
            generated
                .fingerprint()
                .bytes()
                .all(|b| b.is_ascii_hexdigit())
        );
        assert_eq!(generated.certificate(), loaded.certificate());
        loaded.acceptor().unwrap();

        use std::os::unix::fs::PermissionsExt as _;
        let mode = std::fs::File::open(&paths.private_key)
            .unwrap()
            .metadata()
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600);

        // A second generation never replaces a pinned identity.
        let error = match Identity::generate(&paths, &[]) {
            Ok(_) => panic!("a pinned identity was replaced"),
            Err(error) => error.to_string(),
        };
        assert!(error.contains("already exists"), "{error}");
        assert_eq!(
            Identity::load(&paths).unwrap().fingerprint(),
            generated.fingerprint()
        );
    }

    #[test]
    fn certificate_names_are_the_listener_addresses() {
        let addresses = [
            "192.168.0.149:7265".parse().unwrap(),
            "127.0.0.1:7265".parse().unwrap(),
            "192.168.0.149:7266".parse().unwrap(),
        ];
        assert_eq!(
            names_for_addresses(&addresses),
            vec!["127.0.0.1".to_string(), "192.168.0.149".to_string()]
        );
        assert!(names_for_addresses(&[]).is_empty());
    }
}
