---
services:
  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    container_name: blackbox-ngircd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - ./config:/config
    ports:
      - "192.168.0.251:6667:6667"
    restart: unless-stopped
