//! Explicit placement of durable rules; unspecified entries remain inline.
use super::*;
use bbox_util::guidance::{GuidanceFile, generation_files};
use rmcp::schemars;

#[derive(
    Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema,
)]
#[serde(tag = "placement", rename_all = "snake_case")]
pub enum RenderPlacement {
    #[default]
    Inline,
    Satellite {
        topic: GuidanceTopic,
    },
}
impl RenderPlacement {
    pub fn is_inline(&self) -> bool {
        matches!(self, Self::Inline)
    }
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, schemars::JsonSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum GuidanceTopic {
    Retrieval,
    Persistence,
    Orchestration,
    Operations,
    Build,
    Architecture,
    Refactoring,
    Authoring,
    Shell,
}
impl GuidanceTopic {
    pub fn slug(self) -> &'static str {
        match self {
            Self::Retrieval => "retrieval",
            Self::Persistence => "persistence",
            Self::Orchestration => "orchestration",
            Self::Operations => "operations",
            Self::Build => "build",
            Self::Architecture => "architecture",
            Self::Refactoring => "refactoring",
            Self::Authoring => "authoring",
            Self::Shell => "shell",
        }
    }
    pub fn load_when(self) -> &'static str {
        match self {
            Self::Retrieval => "Retrieving code evidence, prior decisions, or conversation history",
            Self::Persistence => "Creating, changing, or retiring durable memory",
            Self::Orchestration => "Dispatching, supervising, or validating agents and Fleet",
            Self::Operations => {
                "Operating or troubleshooting Blackbox infrastructure, configuration, or substrate gaps"
            }
            Self::Build => "Building, formatting, or testing this project",
            Self::Architecture => {
                "Changing subsystem boundaries, protocols, or public tool surfaces"
            }
            Self::Refactoring => "Changing or executing structural refactor tooling",
            Self::Authoring => {
                "Writing project documentation, prompts, research, specifications, or system memories"
            }
            Self::Shell => "Running shell commands on this host",
        }
    }
}

impl Knowledge {
    pub(super) fn guidance_files(
        &self,
        provider: &str,
        filter: ScopeFilter<'_>,
    ) -> Vec<GuidanceFile> {
        let topics: BTreeSet<_> = self
            .renderable_entries()
            .filter(|e| filter.matches(e) && entry_visible_to(e, provider))
            .filter_map(|e| match e.render_placement {
                RenderPlacement::Satellite { topic } => Some(topic),
                _ => None,
            })
            .collect();
        generation_files(
            topics
                .into_iter()
                .map(|topic| {
                    let mut body =
                        String::from("<!-- Generated by blackbox. Do not edit directly. -->\n\n");
                    let include = |e: &KnowledgeEntry| {
                        e.render_placement == RenderPlacement::Satellite { topic }
                    };
                    self.render_steerage_filtered(provider, filter, &mut body, include);
                    self.render_memory_filtered(provider, filter, &mut body, include);
                    (format!("{provider}-{}", topic.slug()), body)
                })
                .collect(),
        )
    }

    pub(super) fn render_guidance_breadcrumbs(
        &self,
        provider: &str,
        filter: ScopeFilter<'_>,
        root: &Path,
        out: &mut String,
    ) {
        let files = self.guidance_files(provider, filter);
        if files.is_empty() {
            return;
        }
        out.push_str("## Task guides\n\nRead the matching guide before that operation. Skip unrelated guides. Read a guide once unless its contents change or are no longer available in context.\n\n");
        for file in files {
            let topic = self
                .renderable_entries()
                .filter(|e| filter.matches(e) && entry_visible_to(e, provider))
                .find_map(|e| match e.render_placement {
                    RenderPlacement::Satellite { topic }
                        if file
                            .path
                            .ends_with(&format!("-{slug}.md", slug = topic.slug())) =>
                    {
                        Some(topic)
                    }
                    _ => None,
                })
                .expect("satellite has a registered topic");
            out.push_str(&format!(
                "- {}: `{}`\n",
                topic.load_when(),
                root.join(file.path).display()
            ));
        }
        out.push('\n');
    }
}
