//! Provider projections of durable knowledge entries.
//!
//! Every renderer (the daemon's global and project render, the bound harness
//! locality client, and the checkout-owner collector) derives provider bodies
//! and guidance satellites from these functions, so an owner-applied render
//! produces the same bytes the daemon would.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::Path;

use anyhow::Result;
use bbox_util::guidance::{GuidanceFile, generation_files};

use crate::model::{Approval, Category, KnowledgeEntry, RenderPlacement, Scope, Status};

pub const PROJECT_DOC_FILE: &str = "PROJECT.md";
pub const GENERATED_MARKER: &str = "<!-- Generated by blackbox";
pub const PROJECT_PROVIDERS: [&str; 3] = ["claude", "agents", "gemini"];

/// Which rows a body renders: global rows, or project rows whose durable
/// scope or project id equals the selector.
#[derive(Clone, Copy, Debug)]
pub enum ScopeFilter<'a> {
    Global,
    Project(&'a str),
}

impl<'a> ScopeFilter<'a> {
    pub fn matches(&self, entry: &KnowledgeEntry) -> bool {
        match (self, &entry.scope) {
            (ScopeFilter::Global, Scope::Global) => true,
            (ScopeFilter::Project(selector), Scope::Project) => {
                entry.project.as_deref() == Some(*selector)
                    || entry.project_id.as_deref() == Some(*selector)
            }
            _ => false,
        }
    }
}

/// Active, unexpired, and not indexed-only. `now` is an ISO-8601 instant;
/// expiry compares ISO strings, which order chronologically.
pub fn is_renderable(entry: &KnowledgeEntry, now: &str) -> bool {
    entry.status == Status::Active
        && entry
            .expires_at
            .as_deref()
            .is_none_or(|expires| expires >= now)
        && entry.render
}

pub fn entry_visible_to(entry: &KnowledgeEntry, provider: &str) -> bool {
    if entry.providers.is_empty() {
        return true;
    }
    if provider == "agents" {
        // AGENTS.md serves codex + vibe
        return entry.providers.iter().any(|p| p == "codex" || p == "vibe");
    }
    entry.providers.iter().any(|p| p == provider)
}

/// The renderable rows of one entry set, in source order.
pub struct Projection<'a> {
    entries: Vec<&'a KnowledgeEntry>,
}

impl<'a> Projection<'a> {
    pub fn new(entries: impl IntoIterator<Item = &'a KnowledgeEntry>) -> Self {
        Self::at(entries, &bbox_util::util::now_iso())
    }

    pub fn at(entries: impl IntoIterator<Item = &'a KnowledgeEntry>, now: &str) -> Self {
        Self {
            entries: entries
                .into_iter()
                .filter(|entry| is_renderable(entry, now))
                .collect(),
        }
    }

    pub fn renderable_entries(&self) -> impl Iterator<Item = &'a KnowledgeEntry> + '_ {
        self.entries.iter().copied()
    }

    pub fn render_steerage(&self, provider: &str, filter: ScopeFilter, md: &mut String) {
        self.render_steerage_filtered(provider, filter, md, |e| e.render_placement.is_inline());
    }

    pub fn render_steerage_filtered<F>(
        &self,
        provider: &str,
        filter: ScopeFilter,
        md: &mut String,
        include: F,
    ) where
        F: Fn(&KnowledgeEntry) -> bool,
    {
        let heading = match provider {
            "claude" => "## Standing Orders",
            "gemini" => "## Foundational Mandates",
            _ => "## Critical Instructions",
        };

        let steerage: Vec<&KnowledgeEntry> = self
            .renderable_entries()
            .filter(|e| e.category == Category::Steering)
            .filter(|e| entry_visible_to(e, provider))
            .filter(|e| filter.matches(e))
            .filter(|e| include(e))
            .collect();

        if !steerage.is_empty() {
            md.push_str(heading);
            md.push('\n');
            md.push('\n');
            render_entries(&steerage, provider, md);
            md.push('\n');
        }
    }

    pub fn render_memory(&self, provider: &str, filter: ScopeFilter, md: &mut String) {
        self.render_memory_filtered(provider, filter, md, |e| e.render_placement.is_inline());
    }

    pub fn render_memory_filtered<F>(
        &self,
        provider: &str,
        filter: ScopeFilter,
        md: &mut String,
        include: F,
    ) where
        F: Fn(&KnowledgeEntry) -> bool,
    {
        let memory_categories = [
            Category::Profile,
            Category::Convention,
            Category::Build,
            Category::Tool,
            Category::Memory,
            Category::Workflow,
        ];

        let mut by_category: HashMap<&str, Vec<&KnowledgeEntry>> = HashMap::new();
        for entry in self.renderable_entries() {
            if entry.category == Category::Steering {
                continue;
            }
            if !entry_visible_to(entry, provider) {
                continue;
            }
            if !filter.matches(entry) {
                continue;
            }
            if !include(entry) {
                continue;
            }
            let heading = entry.category.heading();
            by_category.entry(heading).or_default().push(entry);
        }

        for cat in &memory_categories {
            let heading = cat.heading();
            if let Some(entries) = by_category.get(heading) {
                let mut sorted = entries.clone();
                sorted.sort_by(|a, b| {
                    a.weight
                        .cmp(&b.weight)
                        .then_with(|| a.title.cmp(&b.title))
                        .then_with(|| a.id.cmp(&b.id))
                });
                md.push_str(&format!("## {}\n\n", heading));
                render_entries_grouped(&sorted, provider, md);
                md.push('\n');
            }
        }
    }

    /// Content-addressed satellites for every satellite topic visible to
    /// `provider` under `filter`.
    pub fn guidance_files(&self, provider: &str, filter: ScopeFilter<'_>) -> Vec<GuidanceFile> {
        let topics: BTreeSet<_> = self
            .renderable_entries()
            .filter(|e| filter.matches(e) && entry_visible_to(e, provider))
            .filter_map(|e| match e.render_placement {
                RenderPlacement::Satellite { topic } => Some(topic),
                _ => None,
            })
            .collect();
        generation_files(
            topics
                .into_iter()
                .map(|topic| {
                    let mut body =
                        String::from("<!-- Generated by blackbox. Do not edit directly. -->\n\n");
                    let include = |e: &KnowledgeEntry| {
                        e.render_placement == RenderPlacement::Satellite { topic }
                    };
                    self.render_steerage_filtered(provider, filter, &mut body, include);
                    self.render_memory_filtered(provider, filter, &mut body, include);
                    (format!("{provider}-{}", topic.slug()), body)
                })
                .collect(),
        )
    }

    pub fn render_guidance_breadcrumbs(
        &self,
        provider: &str,
        filter: ScopeFilter<'_>,
        root: &Path,
        out: &mut String,
    ) {
        let files = self.guidance_files(provider, filter);
        if files.is_empty() {
            return;
        }
        out.push_str("## Task guides\n\nRead the matching guide before that operation. Skip unrelated guides. Read a guide once unless its contents change or are no longer available in context.\n\n");
        for file in files {
            let topic = self
                .renderable_entries()
                .filter(|e| filter.matches(e) && entry_visible_to(e, provider))
                .find_map(|e| match e.render_placement {
                    RenderPlacement::Satellite { topic }
                        if file
                            .path
                            .ends_with(&format!("-{slug}.md", slug = topic.slug())) =>
                    {
                        Some(topic)
                    }
                    _ => None,
                })
                .expect("satellite has a registered topic");
            out.push_str(&format!(
                "- {}: `{}`\n",
                topic.load_when(),
                root.join(file.path).display()
            ));
        }
        out.push('\n');
    }

    /// Body for a project file: project-scope steerage, project-scope memory,
    /// a conditional PROJECT.md breadcrumb, and satellite breadcrumbs. No
    /// global content.
    pub fn project_body(
        &self,
        provider: &str,
        scope_selector: &str,
        project_doc_nonempty: bool,
    ) -> String {
        let mut body = String::new();
        let filter = ScopeFilter::Project(scope_selector);

        self.render_steerage(provider, filter, &mut body);

        // Gemini deprioritizes content at the bottom, so PROJECT.md goes
        // between steerage and memory instead of after both.
        if provider == "gemini" {
            render_project_include(provider, project_doc_nonempty, &mut body);
            self.render_memory(provider, filter, &mut body);
        } else {
            self.render_memory(provider, filter, &mut body);
            render_project_include(provider, project_doc_nonempty, &mut body);
        }

        self.render_guidance_breadcrumbs(provider, filter, Path::new(".bbox"), &mut body);
        body
    }

    /// The complete generated provider file, or `None` when it has no body.
    pub fn project_projection(
        &self,
        provider: &str,
        scope_selector: &str,
        project_doc_nonempty: bool,
    ) -> Option<String> {
        finish_project_projection(self.project_body(provider, scope_selector, project_doc_nonempty))
    }
}

pub fn finish_project_projection(body: String) -> Option<String> {
    if body.trim().is_empty() {
        return None;
    }
    let mut full = String::new();
    full.push_str("<!-- Generated by blackbox. Do not edit directly. -->\n");
    full.push_str("<!-- Use bbox_learn / bbox_forget to modify. -->\n\n");
    full.push_str(body.trim_end());
    full.push('\n');
    Some(full)
}

pub fn render_entries(entries: &[&KnowledgeEntry], provider: &str, out: &mut String) {
    for entry in entries {
        let mark = match entry.approval {
            Approval::AgentInferred => " *(unverified)*",
            Approval::Imported => " *(imported)*",
            _ => "",
        };
        // Always render title if non-empty, not just for unverified entries
        if !entry.title.is_empty() {
            out.push_str(&format!("**{}**{}\n\n", entry.title, mark));
        }
        // Use provider-specific variant if available, else default content
        let content = entry.variants.get(provider).unwrap_or(&entry.content);
        out.push_str(content);
        out.push_str("\n\n");
    }
}

pub fn render_entries_grouped(entries: &[&KnowledgeEntry], provider: &str, out: &mut String) {
    let mut unclustered = Vec::new();
    let mut clustered: BTreeMap<&str, Vec<&KnowledgeEntry>> = BTreeMap::new();

    for entry in entries {
        match entry.cluster.as_deref() {
            Some(cluster) if !cluster.trim().is_empty() => {
                clustered.entry(cluster).or_default().push(*entry);
            }
            _ => unclustered.push(*entry),
        }
    }

    if !unclustered.is_empty() {
        render_entries(&unclustered, provider, out);
    }

    for (cluster, grouped) in clustered {
        out.push_str(&format!("### {}\n\n", cluster));
        render_entries(&grouped, provider, out);
        out.push('\n');
    }
}

fn project_include_instruction(_provider: &str) -> &'static str {
    "For project architecture, implementation, or operational work, read `PROJECT.md`. Skip it for unrelated tasks."
}

pub fn render_project_include(provider: &str, project_doc_nonempty: bool, md: &mut String) {
    if project_doc_nonempty {
        md.push_str(project_include_instruction(provider));
        md.push('\n');
    }
}

/// The providers one project render request selects, each validated to own a
/// fixed project file.
pub fn validated_project_render_providers(provider: Option<&str>) -> Result<Vec<&str>> {
    let providers = provider
        .map(|provider| vec![provider])
        .unwrap_or_else(|| PROJECT_PROVIDERS.to_vec());
    for provider in &providers {
        project_target_file(provider)?;
    }
    Ok(providers)
}

/// The fixed checkout-root file a provider's project projection occupies.
pub fn project_target_file(provider: &str) -> Result<&'static str> {
    match provider {
        "claude" => Ok("CLAUDE.md"),
        "agents" | "codex" | "vibe" => Ok("AGENTS.md"),
        "gemini" => Ok("GEMINI.md"),
        other => anyhow::bail!(
            "unsupported project render provider {other:?}; expected claude, agents, codex, vibe, or gemini"
        ),
    }
}

/// Whether the checkout carries a non-empty regular PROJECT.md.
#[allow(
    clippy::disallowed_methods,
    reason = "Synchronous renderer IO; daemon callers run on the blocking pool and owner callers are synchronous"
)]
pub fn project_doc_nonempty(project_dir: &Path) -> bool {
    std::fs::metadata(project_dir.join(PROJECT_DOC_FILE))
        .map(|metadata| metadata.is_file() && metadata.len() > 0)
        .unwrap_or(false)
}
