use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Built-in tool documentation rendered into CLAUDE.md / AGENTS.md / GEMINI.md.
///
/// These sections are generated by the server — not stored as knowledge entries.
/// They serve two purposes:
/// 1. Teach workflow patterns (HOW/WHEN/WHY), not just tool descriptions
/// 2. List all tools so deferred-loading LLMs discover them before improvising
pub const MANAGED_START: &str = "<!-- bb:managed-start -->";
pub const MANAGED_END: &str = "<!-- bb:managed-end -->";

/// A managed region this large is durable operator guidance, not a tiny
/// bootstrap pointer. Refuse to discard more than half of it in one ordinary
/// render. This catches incomplete source views while still allowing routine
/// edits and small generated regions to evolve normally.
const MIN_SHRINK_PROTECTED_BYTES: usize = 512;
const MAX_UNACKNOWLEDGED_SHRINK_DIVISOR: usize = 2;

/// Test binaries must never inspect or rewrite the operator's real global
/// guidance files. Unit tests compile this crate with `cfg(test)`; nextest
/// also marks integration-test processes through its runtime environment.
fn running_under_test_harness() -> bool {
    cfg!(test)
        || ["NEXTEST", "NEXTEST_RUN_ID", "NEXTEST_EXECUTION_MODE"]
            .iter()
            .any(|key| std::env::var_os(key).is_some())
}

fn host_global_target_env_key(path: &Path, home: &Path) -> Option<&'static str> {
    [
        (
            home.join(".blackbox").join("BLACKBOX.md"),
            "BLACKBOX_GLOBAL_COMMON_MD",
        ),
        (
            home.join(".claude").join("CLAUDE.md"),
            "BLACKBOX_GLOBAL_CLAUDE_MD",
        ),
        (
            home.join(".codex").join("AGENTS.md"),
            "BLACKBOX_GLOBAL_CODEX_MD",
        ),
        (
            home.join(".gemini").join("GEMINI.md"),
            "BLACKBOX_GLOBAL_GEMINI_MD",
        ),
    ]
    .into_iter()
    .find_map(|(default, env_key)| (path == default).then_some(env_key))
}

fn default_global_knowledge_source(home: &Path) -> PathBuf {
    dirs::state_dir()
        .unwrap_or_else(|| home.join(".local").join("state"))
        .join("blackbox")
        .join("blackbox-knowledge.json")
}

fn paths_name_same_object(left: &Path, right: &Path) -> bool {
    left == right
        || matches!(
            (left.canonicalize(), right.canonicalize()),
            (Ok(left), Ok(right)) if left == right
        )
}

fn env_path_is_explicit(env_key: &str) -> bool {
    std::env::var_os(env_key).is_some_and(|value| !value.is_empty())
}

/// Refuse to let an isolated knowledge store publish into a host-default
/// global guidance file by accident.
///
/// A daemon that moves its state or knowledge store is a distinct source
/// authority. It must move each global render target too, or explicitly bind
/// that target through its documented environment variable. This catches the
/// dangerous partial-isolation shape where a throwaway daemon renders its
/// empty bootstrap view over the operator's production guidance.
pub fn validate_global_render_authority(knowledge_store: &Path, target: &Path) -> Result<()> {
    let home = dirs::home_dir().context("home directory not found")?;
    let Some(target_env_key) = host_global_target_env_key(target, &home) else {
        return Ok(());
    };
    if env_path_is_explicit(target_env_key)
        || paths_name_same_object(knowledge_store, &default_global_knowledge_source(&home))
    {
        return Ok(());
    }
    anyhow::bail!(
        "error.global_render_authority: refusing to render knowledge source {} into the default \
         host guidance target {}. An isolated daemon must set {} to its own target; set that \
         variable explicitly only when this non-default knowledge source is intentionally \
         authoritative for the host target",
        knowledge_store.display(),
        target.display(),
        target_env_key,
    )
}

fn refuse_test_host_global_target(path: &Path) -> Result<()> {
    if !running_under_test_harness() {
        return Ok(());
    }
    let Some(home) = dirs::home_dir() else {
        return Ok(());
    };
    let Some(env_key) = host_global_target_env_key(path, &home) else {
        return Ok(());
    };
    anyhow::bail!(
        "refusing test-process access to host global guidance file {}; route {} to a test fixture",
        path.display(),
        env_key
    )
}

/// Resolve global-memory destinations per provider. Returns `None` for
/// providers without a defined global memory file (copilot reads project
/// files only; vibe is intentionally unsupported per design).
///
/// Env overrides take precedence over defaults:
/// `BLACKBOX_GLOBAL_CLAUDE_MD`, `BLACKBOX_GLOBAL_CODEX_MD`,
/// `BLACKBOX_GLOBAL_GEMINI_MD`.
pub fn global_target_path(provider: &str) -> Option<Result<PathBuf>> {
    let resolve = |env_key: &str, default_fn: &dyn Fn() -> Result<PathBuf>| -> Result<PathBuf> {
        if let Ok(v) = std::env::var(env_key) {
            return Ok(PathBuf::from(v));
        }
        default_fn()
    };

    let home = || dirs::home_dir().context("home directory not found");

    match provider {
        "claude" => Some(resolve("BLACKBOX_GLOBAL_CLAUDE_MD", &|| {
            Ok(home()?.join(".claude").join("CLAUDE.md"))
        })),
        // "agents" is the render umbrella that produces AGENTS.md content;
        // globally, the only auto-loading consumer is Codex.
        "codex" | "agents" => Some(resolve("BLACKBOX_GLOBAL_CODEX_MD", &|| {
            Ok(home()?.join(".codex").join("AGENTS.md"))
        })),
        "gemini" => Some(resolve("BLACKBOX_GLOBAL_GEMINI_MD", &|| {
            Ok(home()?.join(".gemini").join("GEMINI.md"))
        })),
        _ => None,
    }
}

/// Shared global-memory destination for provider-neutral content. Provider
/// global files stay small and include this by reference.
///
/// Lives under `~/.blackbox/` — provider-neutral by design. Historical
/// location was `~/.claude-shared/BLACKBOX.md`; that path now serves as a
/// back-compat symlink (see `migrate_legacy_defaults`).
///
/// Env override: `BLACKBOX_GLOBAL_COMMON_MD`.
pub fn global_common_target_path() -> Result<PathBuf> {
    let home = dirs::home_dir().context("home directory not found")?;
    Ok(crate::util::blackbox_global_common_md_path(&home))
}

/// A planned managed-region patch. Each variant carries exactly the data
/// relevant to its case — no optionals, no "this field is only set for
/// that outcome" foot-guns. `apply_managed_patch` pattern-matches on this
/// to do the right thing.
#[derive(Debug, Clone)]
pub enum PatchPlan {
    /// File didn't exist; will be created with `managed_block` as the
    /// entire contents.
    Create {
        path: PathBuf,
        managed_block: String,
    },
    /// File exists but has no markers; `managed_block` will be appended
    /// to `existing_file` (preserving hand-authored content above).
    Append {
        path: PathBuf,
        existing_file: String,
        managed_block: String,
    },
    /// File exists with markers; content between them will be replaced.
    /// `existing_block` includes both markers.
    Replace {
        path: PathBuf,
        existing_block: String,
        managed_block: String,
    },
    /// File exists with markers and their content already matches what
    /// we'd render; nothing to do.
    Unchanged { path: PathBuf },
}

impl PatchPlan {
    /// The new managed block that would be written. `Unchanged` returns
    /// `None` because the point of that variant is that we won't write.
    pub fn managed_block(&self) -> Option<&str> {
        match self {
            Self::Create { managed_block, .. }
            | Self::Append { managed_block, .. }
            | Self::Replace { managed_block, .. } => Some(managed_block),
            Self::Unchanged { .. } => None,
        }
    }

    /// Text that represents "what's there now," formatted for dry-run
    /// display. Semantics differ per variant: for Append this is the
    /// whole file (will be preserved); for Replace it's just the block
    /// between markers (will be replaced).
    pub fn before_text(&self) -> Option<&str> {
        match self {
            Self::Create { .. } | Self::Unchanged { .. } => None,
            Self::Append { existing_file, .. } => Some(existing_file),
            Self::Replace { existing_block, .. } => Some(existing_block),
        }
    }

    pub fn summary(&self) -> String {
        match self {
            Self::Create {
                path,
                managed_block,
            } => {
                format!("CREATE {} ({} chars)", path.display(), managed_block.len())
            }
            Self::Append {
                path,
                existing_file,
                managed_block,
            } => format!(
                "APPEND managed region to {} (existing {} chars, adding {} chars)",
                path.display(),
                existing_file.len(),
                managed_block.len()
            ),
            Self::Replace {
                path,
                existing_block,
                managed_block,
            } => format!(
                "REPLACE managed region in {} ({} chars → {} chars)",
                path.display(),
                existing_block.len(),
                managed_block.len()
            ),
            Self::Unchanged { path } => format!("UNCHANGED {}", path.display()),
        }
    }
}

/// Compute what a managed-region patch would do without writing anything.
/// `managed_body` is the bbox-rendered content (without markers).
pub fn plan_managed_patch(file_path: &Path, managed_body: &str) -> Result<PatchPlan> {
    refuse_test_host_global_target(file_path)?;
    let managed_block = format!(
        "{MANAGED_START}\n{}\n{MANAGED_END}",
        managed_body.trim_end()
    );
    let path = file_path.to_path_buf();

    if !file_path.exists() {
        return Ok(PatchPlan::Create {
            path,
            managed_block,
        });
    }

    let existing = fs::read_to_string(file_path)
        .with_context(|| format!("reading {}", file_path.display()))?;
    let (start_idx, end_idx) = find_marker_positions(&existing)?;

    match (start_idx, end_idx) {
        (Some(s), Some(e)) => {
            let existing_block = existing[s..e + MANAGED_END.len()].to_string();
            if existing_block == managed_block {
                Ok(PatchPlan::Unchanged { path })
            } else {
                Ok(PatchPlan::Replace {
                    path,
                    existing_block,
                    managed_block,
                })
            }
        }
        (None, None) => Ok(PatchPlan::Append {
            path,
            existing_file: existing,
            managed_block,
        }),
        _ => anyhow::bail!(
            "{}: unbalanced managed-region markers — refusing to patch",
            file_path.display()
        ),
    }
}

/// Apply a `PatchPlan`. Snapshots the original (when a file already exists
/// and we're actually changing it) to the backup directory before writing.
/// Returns the backup path, if a snapshot was taken.
///
/// By default (`allow_destructive_shrink=false`), refuses to replace a
/// substantial managed region with a candidate less than half its size. An
/// empty candidate is the degenerate case. Large unexpected shrinkage is a
/// strong signal that the render source view is incomplete.
pub fn apply_managed_patch(
    plan: &PatchPlan,
    allow_destructive_shrink: bool,
) -> Result<Option<PathBuf>> {
    let path = match plan {
        PatchPlan::Create { path, .. }
        | PatchPlan::Append { path, .. }
        | PatchPlan::Replace { path, .. }
        | PatchPlan::Unchanged { path } => path,
    };
    refuse_test_host_global_target(path)?;

    match plan {
        // Nothing to do — and no empty backup dir, either.
        PatchPlan::Unchanged { .. } => Ok(None),

        PatchPlan::Create {
            path,
            managed_block,
        } => {
            create_parent_dir(path);
            write_atomic(path, &format!("{managed_block}\n"))?;
            Ok(None)
        }

        PatchPlan::Append {
            path,
            existing_file,
            managed_block,
        } => {
            let backup = Some(snapshot_file(path)?);
            let sep = if existing_file.ends_with("\n\n") || existing_file.is_empty() {
                ""
            } else if existing_file.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            create_parent_dir(path);
            write_atomic(path, &format!("{existing_file}{sep}{managed_block}\n"))?;
            Ok(backup)
        }

        PatchPlan::Replace {
            path,
            existing_block,
            managed_block,
        } => {
            if !allow_destructive_shrink {
                let new_body = managed_body_trimmed(managed_block);
                let existing_body = managed_body_trimmed(existing_block);
                if destructive_managed_shrink(existing_body.len(), new_body.len()) {
                    anyhow::bail!(
                        "error.render_destructive_shrink: refusing to replace the managed region \
                         in {}: the candidate is {} bytes but the existing region is {} bytes. \
                         The rendered source view may be incomplete; inspect a dry run and \
                         restore source authority before retrying",
                        path.display(),
                        new_body.len(),
                        existing_body.len(),
                    );
                }
            }
            let backup = Some(snapshot_file(path)?);
            let full = fs::read_to_string(path)?;
            let (s, e) = find_marker_positions(&full)?;
            let s = s.expect("planned Replace requires markers");
            let e = e.expect("planned Replace requires markers");
            let mut out = String::with_capacity(full.len() + managed_block.len());
            out.push_str(&full[..s]);
            out.push_str(managed_block);
            out.push_str(&full[e + MANAGED_END.len()..]);
            if !out.ends_with('\n') {
                out.push('\n');
            }
            create_parent_dir(path);
            write_atomic(path, &out)?;
            Ok(backup)
        }
    }
}

fn destructive_managed_shrink(existing_bytes: usize, candidate_bytes: usize) -> bool {
    (existing_bytes > 0 && candidate_bytes == 0)
        || (existing_bytes >= MIN_SHRINK_PROTECTED_BYTES
            && candidate_bytes.saturating_mul(MAX_UNACKNOWLEDGED_SHRINK_DIVISOR) < existing_bytes)
}

fn create_parent_dir(path: &Path) {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).ok();
        }
    }
}

fn find_marker_positions(text: &str) -> Result<(Option<usize>, Option<usize>)> {
    let starts: Vec<_> = text.match_indices(MANAGED_START).collect();
    let ends: Vec<_> = text.match_indices(MANAGED_END).collect();
    if starts.len() > 1 || ends.len() > 1 {
        anyhow::bail!("multiple managed-region markers found");
    }
    Ok((
        starts.first().map(|(i, _)| *i),
        ends.first().map(|(i, _)| *i),
    ))
}

/// Extract the content between `<!-- bb:managed-start -->` and
/// `<!-- bb:managed-end -->` markers, trimmed. Returns the empty
/// string when the block is malformed or missing markers.
fn managed_body_trimmed(block: &str) -> &str {
    block
        .strip_prefix(MANAGED_START)
        .and_then(|s| s.strip_prefix('\n'))
        .and_then(|s| s.strip_suffix(MANAGED_END))
        .map(|s| s.strip_suffix('\n').unwrap_or(s))
        .map(|s| s.trim())
        .unwrap_or("")
}

/// Snapshot a file to `~/.local/state/blackbox/backups/<ISO-ts>/<filename>`.
/// Returns the destination path. Creates parent dirs as needed.
// render backup snapshots run inside the render handlers' run_blocking closures.
#[allow(clippy::disallowed_methods)]
pub fn snapshot_file(src: &Path) -> Result<PathBuf> {
    let backup_root = backup_root()?;
    let stamp = chrono::Utc::now().format("%Y%m%dT%H%M%SZ").to_string();
    let dir = backup_root.join(stamp);
    fs::create_dir_all(&dir)?;
    let name = src.file_name().context("source path has no file name")?;
    let dest = dir.join(name);
    fs::copy(src, &dest)
        .with_context(|| format!("backing up {} → {}", src.display(), dest.display()))?;
    Ok(dest)
}

fn backup_root() -> Result<PathBuf> {
    if let Ok(v) = std::env::var("BLACKBOX_BACKUP_DIR") {
        return Ok(PathBuf::from(v));
    }
    let state = dirs::state_dir()
        .or_else(|| dirs::home_dir().map(|h| h.join(".local/state")))
        .context("could not locate state dir")?;
    Ok(state.join("blackbox").join("backups"))
}

fn write_atomic(path: &Path, content: &str) -> Result<()> {
    let tmp = path.with_extension("md.tmp");
    let mut file = fs::File::create(&tmp).with_context(|| format!("creating {}", tmp.display()))?;
    file.write_all(content.as_bytes())?;
    file.sync_all()?;
    drop(file);
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} → {}", tmp.display(), path.display()))?;
    Ok(())
}

// ── Global render plan (daemon computes, operator host applies) ──────

/// Schema tag for [`GlobalRenderPlanV1`].
pub const GLOBAL_RENDER_PLAN_KIND_V1: &str = "bbox.global_render_plan.v1";

/// A daemon-computed global render, delivered to an operator host that
/// applies it locally.
///
/// The daemon that owns the knowledge store may not be the host whose
/// provider guidance files should change (a remote daemon renders into its
/// own `$HOME`, which no interactive session reads). The plan carries only
/// the managed bodies; the applying host resolves its own targets through
/// [`global_common_target_path`] / [`global_target_path`], so the host that
/// runs the apply is the target policy. Bodies exclude the managed markers:
/// the applier wraps them with [`plan_managed_patch`] against the real file.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct GlobalRenderPlanV1 {
    /// Always [`GLOBAL_RENDER_PLAN_KIND_V1`].
    pub kind: String,
    /// The applying host's shared include file, as requested by that host.
    /// Provider bodies reference it by this exact path.
    pub host_common_target: String,
    /// Managed body for the shared include (`~/.blackbox/BLACKBOX.md`).
    pub common_body: String,
    /// One managed body per provider global memory file.
    pub providers: Vec<GlobalRenderProviderPlanV1>,
    /// SHA-256 over every body, in order, for receipts and drift checks.
    pub checksum: String,
    /// Source-view diagnostics from the daemon (degraded overlays, legacy
    /// rows). Informational; not covered by the checksum.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub diagnostics: Vec<String>,
}

/// One provider's global memory managed body.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct GlobalRenderProviderPlanV1 {
    /// Render provider key: `claude`, `agents` (Codex `AGENTS.md`), `gemini`.
    pub provider: String,
    pub body: String,
}

impl GlobalRenderPlanV1 {
    pub fn new(
        host_common_target: &Path,
        common_body: String,
        providers: Vec<GlobalRenderProviderPlanV1>,
    ) -> Self {
        let mut plan = Self {
            kind: GLOBAL_RENDER_PLAN_KIND_V1.to_string(),
            host_common_target: host_common_target.display().to_string(),
            common_body,
            providers,
            checksum: String::new(),
            diagnostics: Vec::new(),
        };
        plan.checksum = plan.compute_checksum();
        plan
    }

    fn compute_checksum(&self) -> String {
        use sha2::Digest as _;
        let mut hasher = sha2::Sha256::new();
        hasher.update(self.host_common_target.as_bytes());
        hasher.update([0]);
        hasher.update(self.common_body.as_bytes());
        for provider in &self.providers {
            hasher.update([0]);
            hasher.update(provider.provider.as_bytes());
            hasher.update([0]);
            hasher.update(provider.body.as_bytes());
        }
        hex_lower(&hasher.finalize())
    }

    /// Reject a plan that is not the schema this applier understands, or
    /// whose bodies do not match its checksum.
    pub fn validate(&self) -> Result<()> {
        if self.kind != GLOBAL_RENDER_PLAN_KIND_V1 {
            anyhow::bail!(
                "error.global_render_plan_kind: expected {GLOBAL_RENDER_PLAN_KIND_V1}, got {}",
                self.kind
            );
        }
        let expected = self.compute_checksum();
        if self.checksum != expected {
            anyhow::bail!(
                "error.global_render_plan_checksum: plan bodies do not match checksum {} (computed {expected})",
                self.checksum
            );
        }
        Ok(())
    }
}

fn hex_lower(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes
        .iter()
        .fold(String::with_capacity(bytes.len() * 2), |mut out, byte| {
            let _ = write!(out, "{byte:02x}");
            out
        })
}

/// One applied (or previewed) target of a global render plan.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct GlobalRenderApplyOutcomeV1 {
    /// `common`, or the provider key.
    pub target: String,
    pub path: String,
    /// The [`PatchPlan::summary`] line.
    pub summary: String,
    pub backup: Option<String>,
    /// For dry runs: the managed block that would be written.
    pub managed_block: Option<String>,
}

/// Apply a daemon-computed global render plan on THIS host.
///
/// Targets resolve exactly as a daemon-local global render would resolve
/// them (env overrides, then `$HOME` defaults). The plan's
/// `host_common_target` must equal the resolved common target, otherwise
/// the provider includes would point at a file this host does not render.
/// The destructive-shrink guard applies as usual.
pub fn apply_global_render_plan(
    plan: &GlobalRenderPlanV1,
    dry_run: bool,
) -> Result<Vec<GlobalRenderApplyOutcomeV1>> {
    plan.validate()?;
    let common_target = global_common_target_path()?;
    if !paths_name_same_object(Path::new(&plan.host_common_target), &common_target) {
        anyhow::bail!(
            "error.global_render_plan_target: plan was computed for common target {} but this \
             host resolves {}; request the plan with this host's common target",
            plan.host_common_target,
            common_target.display()
        );
    }
    let mut outcomes = Vec::new();
    let common_plan = plan_managed_patch(&common_target, &plan.common_body)?;
    outcomes.push(apply_one(&common_target, "common", &common_plan, dry_run)?);
    for provider in &plan.providers {
        let Some(target) = global_target_path(&provider.provider) else {
            anyhow::bail!(
                "error.global_render_plan_provider: {} has no documented global memory file",
                provider.provider
            );
        };
        let target = target?;
        let patch = plan_managed_patch(&target, &provider.body)?;
        outcomes.push(apply_one(&target, &provider.provider, &patch, dry_run)?);
    }
    Ok(outcomes)
}

fn apply_one(
    path: &Path,
    label: &str,
    patch: &PatchPlan,
    dry_run: bool,
) -> Result<GlobalRenderApplyOutcomeV1> {
    let backup = if dry_run {
        None
    } else {
        apply_managed_patch(patch, false)?
    };
    Ok(GlobalRenderApplyOutcomeV1 {
        target: label.to_string(),
        path: path.display().to_string(),
        summary: patch.summary(),
        backup: backup.map(|p| p.display().to_string()),
        managed_block: dry_run
            .then(|| patch.managed_block().map(str::to_owned))
            .flatten(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifies_every_host_global_guidance_target() {
        let home = Path::new("/operator-home");
        for (path, env_key) in [
            (
                home.join(".blackbox").join("BLACKBOX.md"),
                "BLACKBOX_GLOBAL_COMMON_MD",
            ),
            (
                home.join(".claude").join("CLAUDE.md"),
                "BLACKBOX_GLOBAL_CLAUDE_MD",
            ),
            (
                home.join(".codex").join("AGENTS.md"),
                "BLACKBOX_GLOBAL_CODEX_MD",
            ),
            (
                home.join(".gemini").join("GEMINI.md"),
                "BLACKBOX_GLOBAL_GEMINI_MD",
            ),
        ] {
            assert_eq!(host_global_target_env_key(&path, home), Some(env_key));
        }
        assert_eq!(
            host_global_target_env_key(Path::new("/fixture/BLACKBOX.md"), home),
            None
        );
    }

    #[test]
    fn test_harness_refuses_real_host_global_guidance_before_reading_it() {
        let home = dirs::home_dir().expect("test host has a home directory");
        let path = home.join(".blackbox").join("BLACKBOX.md");
        let error = plan_managed_patch(&path, "fixture body")
            .expect_err("a test must not inspect the operator's global guidance");
        assert!(
            error.to_string().contains("refusing test-process access"),
            "{error:#}"
        );
    }

    #[test]
    fn nondefault_knowledge_source_cannot_publish_to_implicit_host_target() {
        let mut env = crate::util::TestEnvGuard::new();
        env.remove("BLACKBOX_GLOBAL_COMMON_MD");
        let home = dirs::home_dir().expect("test host has a home directory");
        let target = home.join(".blackbox").join("BLACKBOX.md");
        let source = tempfile::tempdir()
            .unwrap()
            .path()
            .join("blackbox-knowledge.json");

        let error = validate_global_render_authority(&source, &target)
            .expect_err("an isolated source must not inherit the host render target");
        let message = format!("{error:#}");
        assert!(
            message.contains("error.global_render_authority"),
            "{message}"
        );
        assert!(message.contains("BLACKBOX_GLOBAL_COMMON_MD"), "{message}");
    }

    #[test]
    fn explicit_host_target_binding_allows_nondefault_knowledge_source() {
        let home = dirs::home_dir().expect("test host has a home directory");
        let target = home.join(".blackbox").join("BLACKBOX.md");
        let source = tempfile::tempdir()
            .unwrap()
            .path()
            .join("blackbox-knowledge.json");
        let mut env = crate::util::TestEnvGuard::new();
        env.set("BLACKBOX_GLOBAL_COMMON_MD", &target);

        validate_global_render_authority(&source, &target)
            .expect("an explicit source-to-target binding is operator authority");
    }

    #[test]
    fn isolated_target_accepts_isolated_knowledge_source() {
        let fixture = tempfile::tempdir().unwrap();
        let source = fixture.path().join("blackbox-knowledge.json");
        let target = fixture.path().join("BLACKBOX.md");

        validate_global_render_authority(&source, &target)
            .expect("an isolated source and target do not reach host guidance");
    }

    #[test]
    fn test_patch_plan_creates_when_missing() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        let plan = plan_managed_patch(&p, "hello\nworld").unwrap();
        match plan {
            PatchPlan::Create { managed_block, .. } => {
                assert!(managed_block.contains(MANAGED_START));
                assert!(managed_block.contains(MANAGED_END));
                assert!(managed_block.contains("hello"));
            }
            other => panic!("expected Create, got {other:?}"),
        }
    }

    #[test]
    fn test_patch_plan_appends_when_no_markers() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(&p, "user prose\n@RTK.md\n").unwrap();
        let plan = plan_managed_patch(&p, "managed body").unwrap();
        match plan {
            PatchPlan::Append { existing_file, .. } => {
                assert!(existing_file.contains("@RTK.md"));
            }
            other => panic!("expected Append, got {other:?}"),
        }
    }

    #[test]
    fn test_patch_plan_replaces_existing_region() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(
            &p,
            format!("preface\n\n{MANAGED_START}\nold body\n{MANAGED_END}\n\nepilogue\n"),
        )
        .unwrap();
        let plan = plan_managed_patch(&p, "new body").unwrap();
        match plan {
            PatchPlan::Replace {
                existing_block,
                managed_block,
                ..
            } => {
                assert!(existing_block.contains("old body"));
                assert!(managed_block.contains("new body"));
            }
            other => panic!("expected Replace, got {other:?}"),
        }
    }

    #[test]
    fn test_patch_plan_unchanged_when_identical() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        let body = "stable body";
        std::fs::write(&p, format!("{MANAGED_START}\n{body}\n{MANAGED_END}\n")).unwrap();
        let plan = plan_managed_patch(&p, body).unwrap();
        assert!(matches!(plan, PatchPlan::Unchanged { .. }));
    }

    #[test]
    fn test_patch_plan_errors_on_unbalanced_markers() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(&p, format!("preface\n{MANAGED_START}\norphan\n")).unwrap();
        assert!(plan_managed_patch(&p, "body").is_err());
    }

    #[test]
    fn test_apply_patch_preserves_surrounding_content_and_backs_up() {
        let _env = crate::util::test_env_lock();
        let dir = tempfile::tempdir().unwrap();
        let backup_dir = dir.path().join("backups");
        unsafe {
            std::env::set_var("BLACKBOX_BACKUP_DIR", &backup_dir);
        }

        let p = dir.path().join("CLAUDE.md");
        std::fs::write(
            &p,
            format!("@RTK.md\n\n{MANAGED_START}\nold\n{MANAGED_END}\n\n# user notes\n"),
        )
        .unwrap();

        let plan = plan_managed_patch(&p, "fresh").unwrap();
        let backup = apply_managed_patch(&plan, false).unwrap();
        assert!(backup.is_some(), "backup should be taken when file existed");

        let result = std::fs::read_to_string(&p).unwrap();
        assert!(result.starts_with("@RTK.md"), "RTK import preserved");
        assert!(result.contains("# user notes"), "user content preserved");
        assert!(result.contains("fresh"), "new managed body present");
        assert!(!result.contains("\nold\n"), "old managed body replaced");

        unsafe {
            std::env::remove_var("BLACKBOX_BACKUP_DIR");
        }
    }

    #[test]
    fn test_global_target_path_skips_unsupported() {
        assert!(global_target_path("copilot").is_none());
        assert!(global_target_path("vibe").is_none());
        assert!(global_target_path("claude").is_some());
        assert!(global_target_path("codex").is_some());
        assert!(global_target_path("gemini").is_some());
        assert!(global_target_path("agents").is_some());
    }

    // ── clobber-guard tests ──

    #[test]
    fn test_empty_render_over_populated_managed_region_is_refused() {
        let _env = crate::util::test_env_lock();
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().canonicalize().unwrap();
        let backup_dir = root.join("backups");
        unsafe {
            std::env::set_var("BLACKBOX_BACKUP_DIR", &backup_dir);
        }

        let p = root.join("CLAUDE.md");
        let existing_body = "# convention: use rustls, not openssl";
        std::fs::write(
            &p,
            format!("preface\n\n{MANAGED_START}\n{existing_body}\n{MANAGED_END}\n\nepilogue\n"),
        )
        .unwrap();

        // plan a Replace with an empty body (0 entries)
        let plan = plan_managed_patch(&p, "").unwrap();
        assert!(
            matches!(plan, PatchPlan::Replace { .. }),
            "should be a Replace, not {plan:?}"
        );

        // Default safety policy refuses the destructive shrink.
        let err = apply_managed_patch(&plan, false).unwrap_err();
        let msg = format!("{err:#}");
        assert!(
            msg.contains("error.render_destructive_shrink"),
            "error should mention clobber refusal: {msg}"
        );
        assert!(
            msg.contains("CLAUDE.md"),
            "error should name the file: {msg}"
        );

        // file must be unmodified
        let after = std::fs::read_to_string(&p).unwrap();
        assert!(after.contains(existing_body), "managed body preserved");
        assert!(after.contains("epilogue"), "user content preserved");

        unsafe {
            std::env::remove_var("BLACKBOX_BACKUP_DIR");
        }
    }

    #[test]
    fn test_nonempty_stub_cannot_replace_full_global_guidance() {
        let _env = crate::util::test_env_lock();
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().canonicalize().unwrap();
        let backup_dir = root.join("backups");
        unsafe {
            std::env::set_var("BLACKBOX_BACKUP_DIR", &backup_dir);
        }

        let p = root.join("BLACKBOX.md");
        let existing_body = "x".repeat(30_430);
        let incomplete_candidate = "y".repeat(998);
        let original = format!("{MANAGED_START}\n{existing_body}\n{MANAGED_END}\n");
        std::fs::write(&p, &original).unwrap();

        let plan = plan_managed_patch(&p, &incomplete_candidate).unwrap();
        let error = apply_managed_patch(&plan, false)
            .expect_err("a nonempty bootstrap stub must not replace full guidance");
        let message = format!("{error:#}");
        assert!(
            message.contains("error.render_destructive_shrink"),
            "{message}"
        );
        assert!(message.contains("998 bytes"), "{message}");
        assert!(message.contains("30430 bytes"), "{message}");
        assert_eq!(std::fs::read_to_string(&p).unwrap(), original);
        assert!(
            !backup_dir.exists(),
            "a refused render must not create a misleading backup"
        );

        unsafe {
            std::env::remove_var("BLACKBOX_BACKUP_DIR");
        }
    }

    #[test]
    fn test_allow_destructive_shrink_overrides_clobber_guard() {
        let _env = crate::util::test_env_lock();
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().canonicalize().unwrap();
        let backup_dir = root.join("backups");
        unsafe {
            std::env::set_var("BLACKBOX_BACKUP_DIR", &backup_dir);
        }

        let p = root.join("CLAUDE.md");
        std::fs::write(&p, format!("{MANAGED_START}\nold body\n{MANAGED_END}\n")).unwrap();

        let plan = plan_managed_patch(&p, "").unwrap();
        // Explicit internal authority bypasses the guard.
        let backup = apply_managed_patch(&plan, true).unwrap();
        assert!(backup.is_some());

        let result = std::fs::read_to_string(&p).unwrap();
        assert!(!result.contains("old body"), "old managed body replaced");
        // The new block should have empty body between markers
        assert!(result.contains(&format!("{MANAGED_START}\n\n{MANAGED_END}")));

        unsafe {
            std::env::remove_var("BLACKBOX_BACKUP_DIR");
        }
    }

    #[test]
    fn test_nonempty_render_still_succeeds() {
        let _env = crate::util::test_env_lock();
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().canonicalize().unwrap();
        let backup_dir = root.join("backups");
        unsafe {
            std::env::set_var("BLACKBOX_BACKUP_DIR", &backup_dir);
        }

        let p = root.join("CLAUDE.md");
        std::fs::write(&p, format!("{MANAGED_START}\nold\n{MANAGED_END}\n")).unwrap();

        // non-empty body → guard does not fire
        let plan = plan_managed_patch(&p, "new content").unwrap();
        let backup = apply_managed_patch(&plan, false).unwrap();
        assert!(backup.is_some());

        let result = std::fs::read_to_string(&p).unwrap();
        assert!(result.contains("new content"));
        assert!(!result.contains("\nold\n"));

        unsafe {
            std::env::remove_var("BLACKBOX_BACKUP_DIR");
        }
    }

    #[test]
    fn global_render_plan_round_trips_and_checks_its_checksum() {
        let plan = GlobalRenderPlanV1::new(
            Path::new("/host/.blackbox/BLACKBOX.md"),
            "common".into(),
            vec![GlobalRenderProviderPlanV1 {
                provider: "claude".into(),
                body: "claude body".into(),
            }],
        );
        plan.validate().expect("fresh plan validates");
        let json = serde_json::to_string(&plan).unwrap();
        let decoded: GlobalRenderPlanV1 = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded, plan);
        let mut tampered = decoded;
        tampered.common_body.push_str(" drift");
        let error = tampered.validate().expect_err("tampered bodies fail");
        assert!(
            error
                .to_string()
                .contains("error.global_render_plan_checksum"),
            "{error}"
        );
    }

    #[test]
    fn apply_global_render_plan_writes_host_targets_from_daemon_bodies() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().canonicalize().unwrap();
        let common = root.join(".blackbox").join("BLACKBOX.md");
        let claude = root.join(".claude").join("CLAUDE.md");
        let mut env = crate::util::TestEnvGuard::new();
        env.set("BLACKBOX_GLOBAL_COMMON_MD", &common);
        env.set("BLACKBOX_GLOBAL_CLAUDE_MD", &claude);
        env.set("BLACKBOX_BACKUP_DIR", root.join("backups"));
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(&claude, "hand-authored preamble\n").unwrap();

        let plan = GlobalRenderPlanV1::new(
            &common,
            "## Shared\n\nrule one\n".into(),
            vec![GlobalRenderProviderPlanV1 {
                provider: "claude".into(),
                body: format!("@{}\n", common.display()),
            }],
        );

        let preview = apply_global_render_plan(&plan, true).unwrap();
        assert!(!common.exists(), "dry run must not write");
        assert_eq!(preview.len(), 2);
        assert!(preview[0].summary.starts_with("CREATE"), "{preview:?}");
        assert!(preview[1].summary.starts_with("APPEND"), "{preview:?}");

        let applied = apply_global_render_plan(&plan, false).unwrap();
        let common_text = std::fs::read_to_string(&common).unwrap();
        assert!(common_text.contains(MANAGED_START) && common_text.contains("rule one"));
        let claude_text = std::fs::read_to_string(&claude).unwrap();
        assert!(claude_text.starts_with("hand-authored preamble\n"));
        assert!(claude_text.contains(&format!("@{}", common.display())));
        assert!(
            applied[1].backup.is_some(),
            "appending snapshots the original"
        );

        let again = apply_global_render_plan(&plan, false).unwrap();
        assert!(
            again.iter().all(|o| o.summary.starts_with("UNCHANGED")),
            "{again:?}"
        );
    }

    #[test]
    fn apply_global_render_plan_refuses_a_plan_for_another_host_common_target() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().canonicalize().unwrap();
        let mut env = crate::util::TestEnvGuard::new();
        env.set("BLACKBOX_GLOBAL_COMMON_MD", root.join("BLACKBOX.md"));
        let plan = GlobalRenderPlanV1::new(
            Path::new("/somewhere/else/BLACKBOX.md"),
            "body".into(),
            vec![],
        );
        let error = apply_global_render_plan(&plan, true).expect_err("target mismatch");
        assert!(
            error
                .to_string()
                .contains("error.global_render_plan_target"),
            "{error}"
        );
        assert!(!root.join("BLACKBOX.md").exists());
    }
}
